# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-05-29 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoGallery', '0003_auto_20220529_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
